# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Personal Website
email: pereiraryan.rp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experienced Web Developer with a demonstrated history of working in the internet industry. Skilled in front-end frameworks like Angular,Bootstrap Agile Methodologies, DevOps, jQuery,javascript and Java. Strong engineering professional with a Bachelor of Engineering (B.E.) focused in Computer Science from University of Mumbai.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pereiraryan.wordpress.com" # the base hostname & protocol for your site
twitter_username: pereiraryan20
github_username:  pereiraryan

# Build settings
markdown: kramdown

theme: jekyll-theme-merlot